<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net8.0;netstandard2.0</TargetFrameworks>
		<WarningLevel>3</WarningLevel>
		<NoWarn>1573,1591,IDE0054,IDE0063,IDE0074,IDE0090,IDE0290,CA1068,CA1507,CA1512,CA1822,NU1701,NU1904</NoWarn>
		<DocumentationFile>bin/$(Configuration)/$(TargetFramework)/VIEApps.Services.Base.Http.xml</DocumentationFile>
		<RootNamespace>net.vieapps.Services</RootNamespace>
		<AssemblyName>VIEApps.Services.Base.Http</AssemblyName>
		<AssemblyTitle>VIEApps NGX HTTP Service Base</AssemblyTitle>
		<AssemblyVersion>10.10.2604.24</AssemblyVersion>
		<FileVersion>10.10.2604.24</FileVersion>
		<Version>10.10.2604.24</Version>
		<InformationalVersion>10.10.$([System.DateTime]::Now.Year).$([System.DateTime]::Now.Month).$([System.DateTime]::Now.Day)@$(TargetFramework)#blue.ocean</InformationalVersion>
		<Title>VIEApps NGX HTTP Service Base</Title>
		<Description>The base of all HTTP microservices in the VIEApps NGX</Description>
		<Authors>VIEApps.net</Authors>
		<Company>VIEApps.net</Company>
		<Product>VIEApps NGX</Product>
		<Copyright>© $([System.DateTime]::Now.Year) VIEApps.net</Copyright>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageId>VIEApps.Services.Base.Http</PackageId>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>Icon.png</PackageIcon>
		<PackageOutputPath>../../Components</PackageOutputPath>
		<PackageTags>services;microservices;vieapps;vieapps.components;vieapps.services;vieapps.microservices</PackageTags>
		<PackageReleaseNotes>Buy a ticket, please!</PackageReleaseNotes>
		<PackageProjectUrl>https://vieapps.net</PackageProjectUrl>
		<RepositoryUrl>https://github.com/vieapps/Services.Base.Http</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Remove=".DS_Store" />
		<None Remove=".gitattributes" />
		<None Remove=".gitignore" />
		<None Visible="false" Include="README.md" Pack="true" PackagePath="\" />
		<None Visible="false" Include="LICENSE.md" Pack="true" PackagePath="\" />
		<None Visible="false" Include="Icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.AspNetCore" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.HttpOverrides" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Server.IIS" Version="2.2.6" />
		<PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Session" Version="2.3.9" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="VIEApps.Components.Utility.AspNetCore" Version="10.10.2604.24" />
		<PackageReference Include="VIEApps.Services.Base" Version="10.10.2604.24" />
	</ItemGroup>

</Project>